# Generated by Django 5.2.4 on 2025-08-01 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecity',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Favorite Cities'},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at'], 'verbose_name_plural': 'Search History'},
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='conditions',
            field=models.CharField(blank=True, help_text='Weather description', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='humidity',
            field=models.FloatField(blank=True, help_text='Humidity percentage', null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='icon',
            field=models.CharField(blank=True, help_text='Weather icon code', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='pressure',
            field=models.FloatField(blank=True, help_text='Atmospheric pressure in hPa', null=True),
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='wind_speed',
            field=models.FloatField(blank=True, help_text='Wind speed in km/h', null=True),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='city',
            field=models.CharField(help_text="City name in format 'City,CountryCode' (e.g., 'London,UK')", max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Added'),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_cities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(help_text='Searched location', max_length=100),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Search Time'),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_searches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecity',
            unique_together={('user', 'city')},
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['user', 'searched_at'], name='app_searchh_user_id_d041ba_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['city'], name='app_searchh_city_644709_idx'),
        ),
    ]
