# Generated by Django 5.2.4 on 2025-08-15 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_favoritecity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoritecity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-searched_at']},
        ),
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='app_searchh_user_id_d041ba_idx',
        ),
        migrations.RemoveIndex(
            model_name='searchhistory',
            name='app_searchh_city_644709_idx',
        ),
        migrations.AlterUniqueTogether(
            name='favoritecity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='favoritecity',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='favoritecity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='conditions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='icon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='pressure',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='searched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='wind_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='favoritecity',
            unique_together={('user', 'city', 'country_code')},
        ),
    ]
